# Generated by Django 2.2.3 on 2020-02-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='added_jobs',
            name='excluded_sellers',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='added_jobs',
            name='run_status',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
