# Generated by Django 2.2.3 on 2020-02-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_app', '0002_auto_20200209_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check_Ads_One',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('price', models.CharField(blank=True, max_length=200)),
                ('seller_name', models.CharField(blank=True, max_length=200)),
                ('listing_date', models.CharField(blank=True, max_length=200)),
                ('listing_location', models.CharField(blank=True, max_length=200)),
                ('paragraph', models.TextField(blank=True)),
                ('list_attributes', models.CharField(blank=True, max_length=200)),
                ('image_link', models.CharField(blank=True, max_length=200)),
                ('prod_link', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Check_Ads_Two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('price', models.CharField(blank=True, max_length=200)),
                ('seller_name', models.CharField(blank=True, max_length=200)),
                ('listing_date', models.CharField(blank=True, max_length=200)),
                ('listing_location', models.CharField(blank=True, max_length=200)),
                ('paragraph', models.TextField(blank=True)),
                ('list_attributes', models.CharField(blank=True, max_length=200)),
                ('image_link', models.CharField(blank=True, max_length=200)),
                ('prod_link', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
